apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: "2401106"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
      - name: nexus-secret
      containers:
      - name: server
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401106/server:latest
        ports:
        - containerPort: 5000
        env:
        # non-sensitive
        - name: PORT
          value: "5000"
        - name: BASE_URL
          value: "http://server-service.2401106.svc.cluster.local:5000"

        # sensitive: loaded securely from Kubernetes secret
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: JWT_SECRET
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: GMAIL_USER
        - name: GMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: GMAIL_PASS
